# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://example.com" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Malik Krch
  avatar: avatar.png
  gravatar: malik.krechiche@gmail.com # email md5 hash
  description: "Blog personnel" # used by search engines
  
  # Header and footer text
  header_text: >
     <p>« Plus on partage, plus on possède. Voilà le miracle.  »</p>
     
     <p>Malik, je suis lycéen, je suis passionné des métiers du web et de l'image.</p>
  footer_text: >
   Technologies : <a href="http://jekyllrb.com">Jekyll</a> et <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>
  
  # Icons
  rss: false
  email_address: malik.krechiche@outlook.fr # full email address, e.g. "sam@example.com"
  behance: 
  bitbucket: 
  dribbble: 
  facebook: 
  flickr: 
  github: "malikkrch"
  google_plus: 115711538109148806645
  instagram: malik_krch
  linkedin:  # full URL
  pinterest: malik_krch
  reddit: 
  soundcloud: 
  stack_exchange:  # full URL
  steam: kipsafr_com
  tumblr: malikkrch
  twitter: "twitter"
  wordpress: 
  youtube: WeAreYuni
  
  # Scripts
  google_analytics: UA-60251617-1 # tracking id, e.g. "UA-000000-01"
  disqus_shortname: malikkrechiche
  
  # Localization strings
  str_follow_on: "Suivez-moi sur "
  str_rss_follow: "Suivez RSS feed"
  str_email: "Email"
  str_next: "Suivant"
  str_prev: "Précédent"
  str_continue_reading: "Lire la suite"
  
  # Colors, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed